###
######### Used for podman pods to push images
###
apiVersion: v1
kind: Pod
metadata:
  generateName: kaniko-
  labels:
    name: kaniko-app
    tier: devops
spec:
  containers:
    - image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command: 
        - /busybox/cat
      name: kaniko
      tty: true
#       securityContext:
#         privileged: true
#       volumeMounts:
#         - mountPath: /ucd-lib
#           name: ucd-lib
#   volumes:
#     - name: podman-volume
#       persistentVolumeClaim:
#         claimName: podman-volume-pvc ##change here
