###
######### Used for podman pods to push images
###
apiVersion: v1
kind: Pod
metadata:
  generateName: kaniko-
  labels:
    name: kaniko-app
    tier: devops
spec:
  containers:
    - image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command: 
        - /busybox/cat
      name: kaniko
      tty: true
      volumeMounts:
        - mountPath: /kanik-secret
          name: /root
  volumes:
    - name: kanik-secret
      secret:
        secretName: default-dockercfg-sd76r
